### ISSUE TITLE
Installing on windows throws error about shim task

### ISSUE THREAD

**Issue by rasmusfjord** [rgalloni/Auto-GPT-sandbox-wizard#10]
Any ideas on why i get this issue thrown?
Running it in elevated powershell, all is good untill it comes to the following line and throws the error:

Line: CMD ["powershell", "-c", "git config pull.rebase false && ./start_auto_gpt.ps1"]

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "powershell": executable file not found in $PATH: unknown.

**Comment by rgalloni** [comment]
Hello @rasmusfjord 

Auto-GPT is evolving at an incredible speed.

I've updated the .ps1 and .sh script to make them more future-proof.
You should check the latest release :)

Closing this
