### ISSUE TITLE
The Container Image which is getting installed delivers 2 errors

### ISSUE THREAD

**Issue by berndgill** [rgalloni/Auto-GPT-sandbox-wizard#12]
Hello, thanks for that script, but it generates on my MAC with M1 CPU 2 Error Messages:
1) When starting the Auto-GPT, it sending a warning, that: Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file. Could the creation of that file also get included in the script?

2) When using AutoGPT a Google search command can get executed successfully but when a webpage is opened the following error message is published: 
Command browse_website returned: Error: Message: Service /home/appuser/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 255
And form there the bot turns into a loop finding search results in Google and then trying to open them (sometimes it tries to take another browser.

Does anyone know how to overcome that?

**Comment by rgalloni** [comment]
1. Thank you for the suggestion, will change to create auto-gpt.json each time it's updated.
2. It's an issue in the official Dockerfile (this is the current solution: https://github.com/Significant-Gravitas/Auto-GPT/issues/1821#issuecomment-1510350161)
