### ISSUE TITLE
How to restart?

### ISSUE THREAD

**Issue by MediaPublishing** [rgalloni/Auto-GPT-sandbox-wizard#2]
Hi there, I keep getting an error when I'm trying to start a new session. Any idea how to resolve this?
<img width="1182" alt="Error" src="https://user-images.githubusercontent.com/31557155/231009200-1de3a287-5a85-40bc-a052-1c0d1e7ca5b5.png">

**Comment by MediaPublishing** [comment]
P.S.: Thanks for putting this together, very helpful for less tech-savvy users 😎...

**Comment by sekomike910** [comment]
I accidently exited auto GPT and don't know the command to have it start back up to resume tasks. Any guidance would be greatly appreciated. This tool is amazing!

**Comment by julianolungo** [comment]
I typed this into the Terminal and it started again (it's the last line of the auto_gpt_easy_install.sh file):

docker start -ai auto-gpt-container

**Comment by rgalloni** [comment]
@julianolungo that's right. You can also restart the Docker container to produce the same effect. 
I'll specify it in the documentation. Thank you.
