### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'debug'

### ISSUE THREAD

**Issue by jennyqueenofswords** [rgalloni/Auto-GPT-sandbox-wizard#3]
Full error message:

Using memory of type: LocalCache
Traceback (most recent call last):
  File "scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/app/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

**Comment by ManuIbarra** [comment]
Enter nothing to load defaults, enter nothing when finished.
Goal 1:
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Manu\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\Manu\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

Got the same error

**Comment by jennyqueenofswords** [comment]
i figured out how to fix the error, but i don't know how to get to the auto-gpt files lol

anyway, the fix is to change cfg.debug to cfg.debug_mode in the chat.py file (think it's on three lines) maybe someone else has the brain to find where the files are hidden :)

**Comment by rgalloni** [comment]
@jennyqueenofswords Thank you for your help.
I'll fix it in an upcoming release, just wait a few hours :)
