### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by sekomike910** [rgalloni/Auto-GPT-sandbox-wizard#4]
I accidently exited auto GPT by giving the 'n' command when it asked me if I had anything else to add and don't know the command to have it start back up to resume tasks. Any guidance would be greatly appreciated. This tool is amazing!

 Is there anything else you would like me to help you with regarding this goal?
Attempting to fix JSON by finding outermost brackets
Error: Invalid JSON, setting it to empty JSON now.

JARVIS THOUGHTS:
REASONING:
CRITICISM:
Attempting to fix JSON by finding outermost brackets
Error: Invalid JSON, setting it to empty JSON now.

NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'dict' object has no attribute 'replace'
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Jarvis...
Input:N
Exiting...
PS C:\Users\19132\Downloads\Auto-GPT>

**Comment by sekomike910** [comment]
> @sekomike910 This seems to be a GPT-3 related issue. It has appeared many times during my tests since I'm on GPT-3 as well. Can you confirm you're running on GPT-3.5-turbo and not on GPT-4? Have you selected GPT-3 during setup?

@rgalloni I was using GPT 4 but don't recall seeing an option to choose during setup. Also, because I have little brain syndrome and new to this, I really struggled to understand the docker containers. It kept creating new ones and would stop running so now I am using it outside of the container. Thank you for what you put together, it's truly amazing!

**Comment by crossurmind** [comment]
I have been receiving this same error. Upon setting it up, it did not give me the option to select which Chat GPT.

**Comment by rgalloni** [comment]
This issue seems to be related to an old version of Auto-GPT.
