### ISSUE TITLE
error on windows 11 powershell with ps1

### ISSUE THREAD

**Issue by spart0n654** [rgalloni/Auto-GPT-sandbox-wizard#6]
![image](https://user-images.githubusercontent.com/65240716/232196818-da443634-3965-4cc4-81ec-3783877967e0.png)

this is the error I get on windows 11 powershell running as admin

**Comment by spart0n654** [comment]
no changes have been made to the file. I just open with powershell (admin or not) and the window pops up and goes away, when I open in powershell ISE and run the script it gives me these errors instead of just pooping up and going away.

**Comment by edouardaihua** [comment]
Same here

**Comment by rgalloni** [comment]
Thank you @edouardaihua for your answer.
Auto-GPT is evolving at an incredible speed.

I've updated the .ps1 and .sh script to make them more future-proof. You should check the latest release :)

cc. @spart0n654 - I'm closing this issue since it's not releated to the current release
