### ISSUE TITLE
Error with docker client while installing

### ISSUE THREAD

**Issue by ihtrahbusnes** [rgalloni/Auto-GPT-sandbox-wizard#9]
Hi,

I am getting the below error while installing. Could someone please help out? 

Thank you

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22name%22%3A%7B%22auto-gpt-container%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by ihtrahbusnes** [comment]
Also getting this: 

Remove-Item : Cannot find path 'C:\Users\x\cloned_repo' because it does not exist.
At C:\Users\x\auto_gpt_easy_install.ps1:28 char:5
+     Remove-Item -Recurse -Force "cloned_repo"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\x\cloned_repo:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by rgalloni** [comment]
Hello @ihtrahbusnes, you're seeing this error since you don't have your Docker running. Try running it instead.
Also, you'll get this error if trying to run Docker on a non-supported VM! Hope this helps.
